# Generated by Django 4.2.5 on 2023-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0002_menutype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость включения в меню'),
            preserve_default=False,
        ),
    ]
