# Generated by Django 4.2.5 on 2023-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0005_remove_dish_menu_type_dish_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='caloricity',
            field=models.IntegerField(default=100, verbose_name='Калорийность'),
            preserve_default=False,
        ),
    ]
