# Generated by Django 4.2.5 on 2023-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0006_dish_caloricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='measurement',
            field=models.CharField(choices=[('UNIT', 'шт.'), ('GR', 'г.'), ('TASTE', 'по вкусу'), ('GLASS', 'стакан'), ('TBLSP', 'ст. ложка'), ('TSP', 'ч. ложка'), ('LEAF', 'листик'), ('L', 'литр'), ('ML', 'мл.')], default='TASTE', max_length=9, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='foodplan.allergy', verbose_name='Аллергии'),
        ),
    ]
