# Generated by Django 4.2.5 on 2023-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0007_dishingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
