# Generated by Django 4.2.5 on 2023-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0012_alter_dishingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('UNIT', 'шт.'), ('GR', 'г.'), ('TASTE', 'по вкусу'), ('GLASS', 'стак.'), ('TBLSP', 'ст. л.'), ('TSP', 'ч. л.'), ('LEAF', 'лист.'), ('L', 'л.'), ('ML', 'мл.'), ('ROAST', 'для обжарки'), ('SERVE', 'для подачи')], default='TASTE', max_length=9, null=True, verbose_name='Единица измерения'),
        ),
    ]
