# Generated by Django 4.2.5 on 2023-09-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0016_alter_dishingredient_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Приём пищи', 'verbose_name_plural': 'Приёмы пищи'},
        ),
    ]
