# Generated by Django 4.2.5 on 2023-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0018_alter_ingredient_options_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='subscription_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID подписки'),
        ),
    ]
