# Generated by Django 4.2.5 on 2023-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0018_alter_ingredient_options_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание меню'),
        ),
    ]
